//! # Phylon Analytics
//!
//! Metrics collection, population history, diversity indices, spatial
//! heatmaps, lineage tracking, and research report generation.
//!
//! The analytics crate is a pure consumer of the event bus — it never
//! mutates simulation state. It accumulates time-series data and exposes
//! query APIs for the UI and research crates.

#![warn(missing_docs)]
#![warn(clippy::all)]

use common::Tick;
use serde::{Deserialize, Serialize};

/// A single population count sample.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PopulationSample {
    /// The tick at which this sample was recorded.
    pub tick: Tick,
    /// Total organism count across all species.
    pub total: u64,
}

/// A single compute pass timing record.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PassTiming {
    /// Identifier for the compute pass (e.g., "Muscle", "Diffusion").
    pub name: String,
    /// CPU-side estimated duration in milliseconds.
    pub duration_ms: f64,
}

/// Placeholder for the analytics accumulator.
pub struct AnalyticsAccumulator {
    samples: Vec<PopulationSample>,
}

impl AnalyticsAccumulator {
    /// Creates a new empty accumulator.
    pub fn new() -> Self {
        Self {
            samples: Vec::new(),
        }
    }

    /// Records a population sample.
    pub fn record_population(&mut self, tick: Tick, total: u64) {
        self.samples.push(PopulationSample { tick, total });
    }

    /// Returns the number of recorded samples.
    pub fn sample_count(&self) -> usize {
        self.samples.len()
    }
}

impl Default for AnalyticsAccumulator {
    fn default() -> Self {
        Self::new()
    }
}

/// Maximum number of time-series samples to keep in the ring buffers.
const METRICS_RING_CAPACITY: usize = 512;

/// Live simulation metrics resource, held in the ECS world and updated each frame.
///
/// Data is stored as `[sim_time, value]` pairs suitable for direct use with
/// `egui_plot::PlotPoints`.
#[derive(bevy_ecs::prelude::Resource, Debug, Clone)]
pub struct MetricsState {
    /// Ring buffer of `[sim_time_s, entity_count]` points for the population plot.
    pub population_history: std::collections::VecDeque<[f64; 2]>,
    /// Ring buffer of `[sim_time_s, fps]` points for the FPS plot.
    pub fps_history: std::collections::VecDeque<[f64; 2]>,
    /// Accumulated simulation time in seconds.
    pub sim_time: f64,
    /// Smoothed FPS estimate (exponential moving average).
    pub smoothed_fps: f64,
    /// CPU-side timings for the most recent frame's compute passes.
    pub compute_profiles: Vec<PassTiming>,
}

impl MetricsState {
    /// Creates a new, empty `MetricsState`.
    pub fn new() -> Self {
        Self {
            population_history: std::collections::VecDeque::with_capacity(METRICS_RING_CAPACITY),
            fps_history: std::collections::VecDeque::with_capacity(METRICS_RING_CAPACITY),
            sim_time: 0.0,
            smoothed_fps: 60.0,
            compute_profiles: Vec::new(),
        }
    }

    /// Records one simulation frame with the current entity count and frame delta time.
    ///
    /// `dt` is in seconds (typically 0.016 for 60 Hz).
    pub fn record_frame(&mut self, entity_count: usize, sim_dt: f64, real_dt: f64) {
        self.sim_time += sim_dt;

        // Exponential moving average for FPS (α = 0.05)
        let raw_fps = if real_dt > 0.0 { 1.0 / real_dt } else { 60.0 };
        self.smoothed_fps = self.smoothed_fps * 0.95 + raw_fps * 0.05;

        if self.population_history.len() >= METRICS_RING_CAPACITY {
            self.population_history.pop_front();
        }
        self.population_history
            .push_back([self.sim_time, entity_count as f64]);

        if self.fps_history.len() >= METRICS_RING_CAPACITY {
            self.fps_history.pop_front();
        }
        self.fps_history
            .push_back([self.sim_time, self.smoothed_fps]);
    }
}

impl Default for MetricsState {
    fn default() -> Self {
        Self::new()
    }
}

/// A narrative event generated by the simulation.
#[derive(Debug, Clone)]
pub struct NarrativeEvent {
    /// Simulation tick when the event occurred.
    pub tick: u64,
    /// Categorical type of event (e.g. "Lineage", "Hazard", "Global").
    pub event_type: String,
    /// Human-readable description.
    pub description: String,
}

/// Ring buffer resource tracking recent narrative events.
#[derive(bevy_ecs::prelude::Resource, Debug, Clone)]
pub struct NarrationLog {
    /// Buffer of recent events.
    pub events: std::collections::VecDeque<NarrativeEvent>,
    max_events: usize,
}

impl NarrationLog {
    /// Create a new narration log with max capacity.
    pub fn new(max_events: usize) -> Self {
        Self {
            events: std::collections::VecDeque::with_capacity(max_events),
            max_events,
        }
    }

    /// Push a new event. Removes oldest if at capacity.
    pub fn push_event(
        &mut self,
        tick: u64,
        event_type: impl Into<String>,
        description: impl Into<String>,
    ) {
        if self.events.len() >= self.max_events {
            self.events.pop_front();
        }
        self.events.push_back(NarrativeEvent {
            tick,
            event_type: event_type.into(),
            description: description.into(),
        });
    }
}

impl Default for NarrationLog {
    fn default() -> Self {
        Self::new(100)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn accumulator_records_samples() {
        let mut acc = AnalyticsAccumulator::new();
        acc.record_population(Tick(0), 100);
        acc.record_population(Tick(60), 105);
        assert_eq!(acc.sample_count(), 2);
    }

    #[test]
    fn metrics_state_ring_buffer_caps_at_max() {
        let mut m = MetricsState::new();
        for _ in 0..(METRICS_RING_CAPACITY + 10) {
            m.record_frame(42, 0.016, 0.016);
        }
        assert_eq!(m.population_history.len(), METRICS_RING_CAPACITY);
        assert_eq!(m.fps_history.len(), METRICS_RING_CAPACITY);
    }
}
