use crate::components::section_header::section_header;
use crate::theme::{BG_CONTROL, TEXT_MUTED};
use egui::{Color32, RichText, Ui};

pub fn render_research(ui: &mut Ui, script_path: &mut String, load_script: &mut bool) {
    section_header(ui, "Loaded Scripts");

    // Mock list of scripts
    let scripts = [
        (
            "fitness_tracker.rhai",
            "Active",
            Color32::from_rgb(50, 180, 100),
        ),
        ("lineage_exporter.rhai", "Idle", TEXT_MUTED),
    ];

    for (name, status, color) in scripts {
        ui.horizontal(|ui| {
            ui.label(RichText::new("📄"));
            ui.label(RichText::new(name).size(11.0));
            ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                ui.label(RichText::new(status).size(10.0).color(color));
            });
        });
        ui.add_space(4.0);
    }

    ui.add_space(8.0);

    // File picker replacement
    ui.horizontal(|ui| {
        let text_edit = egui::TextEdit::singleline(script_path).desired_width(180.0);
        ui.add(text_edit);

        if ui.button("Browse...").clicked() {
            // In a real app we'd spawn rfd::FileDialog
            *script_path = "scripts/custom_metric.rhai".to_string();
        }
    });

    if ui
        .add(egui::Button::new("Load Script").fill(BG_CONTROL))
        .clicked()
    {
        *load_script = true;
    }

    ui.add_space(16.0);
    section_header(ui, "Active Script Readouts");

    ui.label(
        RichText::new("No custom plots generated by active scripts.")
            .color(TEXT_MUTED)
            .size(11.0),
    );
}
