name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check formatting
      run: cargo fmt --check
    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: Test
      run: cargo nextest run
    - name: Doc
      run: cargo doc --no-deps --document-private-items

